# Site
name: "Balanced body and mind"
title: "Balanced body and mind"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: G-R37FWQX4LY
google_recaptcha_site: 6LcYzZIlAAAAACd7D7et5d5PAc4ZXaH1oiaf-dC5
disqus: 'balancedbodymind'
mailchimp-list: 'https://gmail.us9.list-manage.com/subscribe/post?u=81523f01fb33d05d72cde7372&amp;id=87128929ec'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dilip:
    name: Dilip
    display_name: Dilip    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    bio: "This is the author box. Write a short description of the author here. You are currently previewing B2M."
  eriny:
    name: Eriny
    display_name: Eriny
    gravatar: fbee8be9a742040440ac390973d7855e
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    bio: "This is the author box. Write a short description of the author here. You are currently previewing B2M."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_trail: 2
paginate_show_first_and_last: true
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
